# Shell tools
brew "bat"
brew "direnv"
brew "duf"
brew "fzf"
brew "glow"
brew "lsd"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zoxide"

# Fonts
cask "font-jetbrains-mono-nerd-font"

# Languages
brew "go"
brew "python"

# Runtimes
brew "bun"
brew "deno"
brew "node"

# Dev tools
brew "actionlint"
brew "aws-cdk"
brew "buf"
brew "clang-format"
brew "convco"
brew "evans"
brew "gh"
brew "git"
brew "git-delta"
brew "golangci-lint"
brew "goose"
brew "govulncheck"
brew "lefthook"
brew "mise"
brew "httpie"
brew "jq"
brew "mas"
brew "pgcli"
brew "pnpm"
cask "session-manager-plugin"
brew "shellcheck"
brew "sqlc"
brew "wget"
brew "yq"

# Infra tools
cask "1password-cli"
brew "awscli"
brew "checkov"
brew "colima"
brew "cosign"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
cask "gcloud-cli"
brew "grype"
brew "hadolint"
brew "kubectx"
brew "kubernetes-cli"
brew "stern"
brew "syft"
brew "hashicorp/tap/terraform"
brew "terraform-linters/tap/tflint"
brew "trivy"

# Desktop apps
cask "1password"
cask "brave-browser"
cask "chatgpt"
cask "codex"
cask "claude"
cask "ghostty"
cask "google-chrome"
cask "microsoft-teams"
cask "slack"
cask "visual-studio-code"
mas "Numbers", id: 361304891
mas "Pages", id: 361309726

# VScode extensions
vscode "ms-azuretools.vscode-containers"        # Container Tools
vscode "golang.go"                              # Go
vscode "ms-python.python"                       # Python
vscode "amazonwebservices.aws-toolkit-vscode"   # AWS Toolkit
vscode "hashicorp.terraform"                    # Terraform
vscode "openai.chatgpt"                         # OpenAI Codex
vscode "ms-vscode.live-server"                  # Live Server
vscode "tomoki1207.pdf"                         # vscode-pdf
vscode "esbenp.prettier-vscode"                 # Prettier
vscode "dbaeumer.vscode-eslint"                 # ESLint
vscode "yoavbls.pretty-ts-errors"               # Pretty TypeScript Errors
vscode "catppuccin.catppuccin-vsc"              # Catppuccin Theme
vscode "catppuccin.catppuccin-vsc-icons"        # Catppuccin Icons
vscode "tamasfe.even-better-toml"               # TOML
vscode "bradlc.vscode-tailwindcss"              # Tailwind
vscode "usernamehw.errorlens"                   # Error Lens
vscode "aaron-bond.better-comments"             # Better Comments
vscode "qufiwefefwoyn.inline-sql-syntax"        # Inline SQL
vscode "hashicorp.hcl"				# HashiCorp HCL
