# Refer https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[hostname]
ssh_symbol = ''
ssh_only = false

[username]
format = '[$user]($style)@'
show_always = true

[gcloud]
disabled = true
